### ISSUE TITLE
chunk.forEachModule is not a function

### ISSUE THREAD

**Issue by ThYpHo0n** [eliraz-refael/dts-webpack-bundler#1]
Hey,
I just tried out your webpack plugin and got the following error:

> TypeError: chunk.forEachModule is not a function
    at compilation.chunks.forEach (/path/to/project/node_modules/dts-webpack-bundler/index.js:17:11)
I'm using the following package versions:
`"webpack": "2.4.1",
"dts-webpack-bundler": "^1.0.2",`

For which version of webpack does this plugin work with best?

**Comment by Eliraz-TTK** [comment]
Hey @ThYpHo0n, currently this plugin supports Webpack 3.x
is it a hustle for you to upgrade your webpack?

I'll try to have some support for webpack 2.x by the end of this week, however it is recommend to upgrade so you'll enjoy the tree-shaking feature.

**Comment by ThYpHo0n** [comment]
Thanks, updating to Webpack 3 worked for me :) Just a small hint in the Readme would be nice though ;)

**Comment by eliraz-refael** [comment]
I'll add it to the README. thanks for the heads-up.
if you have any feedback I'd like to get it, thanks!
